IF OBJECT_ID('history.[META__ALL_VALCODES]', 'V') IS NOT NULL
    DROP VIEW history.[META__ALL_VALCODES]
GO

CREATE VIEW history.[META__ALL_VALCODES] AS
SELECT 'CF' AS CDDFILE,
       *       
  FROM history.[META__CF_VALCODES]
UNION
SELECT 'CORE' AS CDDFILE,
       *
  FROM history.[META__CORE_VALCODES]
UNION
SELECT 'HR' AS CDDFILE,
       *
  FROM history.[META__HR_VALCODES]
UNION
SELECT 'ST' AS CDDFILE,
       *
  FROM history.[META__ST_VALCODES]
UNION
SELECT 'TOOL' AS CDDFILE,
       *
  FROM history.[META__TOOL_VALCODES]
UNION
SELECT 'UT' AS CDDFILE,
       *
  FROM history.[META__UT_VALCODES]

