IF OBJECT_ID('history.[META__ALL_VALCODES__VALS]', 'V') IS NOT NULL
    DROP VIEW history.[META__ALL_VALCODES__VALS]
GO

CREATE VIEW history.[META__ALL_VALCODES__VALS] AS
SELECT 'CF' AS VALCODESFILE,
       *       
  FROM history.[META__CF_VALCODES__VALS]
UNION
SELECT 'CORE' AS VALCODESFILE,
       *
  FROM history.[META__CORE_VALCODES__VALS]
UNION
SELECT 'HR' AS VALCODESFILE,
       *
  FROM history.[META__HR_VALCODES__VALS]
UNION
SELECT 'ST' AS VALCODESFILE,
       *
  FROM history.[META__ST_VALCODES__VALS]
UNION
SELECT 'TOOL' AS VALCODESFILE,
       *
  FROM history.[META__TOOL_VALCODES__VALS]
UNION
SELECT 'UT' AS VALCODESFILE,
       *
  FROM history.[META__UT_VALCODES__VALS]

