USE CCDW_HIST
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP VIEW [history].[STUDENT_PROGRAMS__STPR_DATES]
GO
CREATE VIEW [history].[STUDENT_PROGRAMS__STPR_DATES] AS
SELECT [STPR.ACAD.PROGRAM]
     , [STPR.STUDENT]

     , CAST(CASE WHEN LTRIM(RTRIM(CA1.Item))='' THEN '9999-12-31' ELSE LTRIM(RTRIM(CA1.Item)) END AS DATE) AS [STPR.END.DATE]
     , CAST(CASE WHEN LTRIM(RTRIM(CA2.Item))='' THEN '1960-01-01' ELSE LTRIM(RTRIM(CA2.Item)) END AS DATE) AS [STPR.START.DATE]

     , CA1.ItemNumber AS ItemNumber
     , EffectiveDatetime
  FROM [history].[STUDENT_PROGRAMS]
  
CROSS APPLY dw_util.DelimitedSplit8K([STPR.END.DATE],', ') CA1
CROSS APPLY dw_util.DelimitedSplit8K([STPR.START.DATE],', ') CA2
 WHERE COALESCE([STPR.START.DATE],'') != ''
       AND CA1.ItemNumber=CA2.ItemNumber

GO
