 # Define school specific parameters
school:
  name: Your School Name
  abbrev: YSN
  ipeds: 0000000
  fice: 000000
  usgov: 00000
  ncccs: 000
  instid: 0000000

# Define database specific parameters
sql:
  # Name of the database server
  server: ccdw.yourschool.edu
  # Name of the database on the above server
  db: CCDW_DEV
  # Driver for ODBC connections
  driver: ODBC Driver 13 for SQL Server

  ### You should not have to change the following items

  # Schema in above database where loaded data will be uploaded
  schema: input
  # Schema in above database where loaded data will be moved to history
  schema_history: history
  # Schema in above database where final data wharehouse data will be uploaded
  schema_ccdw: ccdw

  # Template file names for create, merge, and alter table statements
  merge_scd1: ../templates/SQL_MERGE_TEMPLATE_SCD1.sql
  merge_scd2: ../templates/SQL_MERGE_TEMPLATE_SCD2.sql
  add_Columns: ../templates/SQL_ALTER_TEMPLATE.sql
  create_view: ../templates/SQL_VIEW_TEMPLATE.sql
  create_view2: ../templates/SQL_VIEW2_TEMPLATE.sql
  create_keys: ../templates/SQL_PRIMARY_KEY_TEMPLATE.sql

# Define informer specific parameters
informer:
  # Full path to root path where export files are located
  export_path: K:/DW/
  export_path_wStatus: K:/DW___wStatus/
  export_path_meta: K:/META/
  export_path_meta_cdd: K:/META/CDD/
  log_path: ./log/
  meta_custom: ./META__CUSTOM_CDD.csv


  # Paths for output and archive files
  archive_path: ../archive/
  archive_path_wStatus: ../archive/wStatus/
  invalid_path_wStatus: ../archive/wStatus_INVALID/

  ###
  ### You should not have to change the following items
  ###
  
  # Prefix for all informer reports
  prefix: DW_
  # The latest version of reports that appear in the above location
  latest_version: 1001
