CREATE TABLE [dw].[DimCourses]
(
	[Courses_Key] INT NOT NULL  IDENTITY, 
    [Terms_Key] INT NOT NULL, 
    [Campus Course ID] NVARCHAR(60) NULL, 
    [Course] NVARCHAR(50) NULL, 
    [Subject Code] NVARCHAR(5) NULL, 
    [Course Number] NVARCHAR(5) NULL, 
    [Section Number] NVARCHAR(5) NULL, 
    [Course Name] NVARCHAR(255) NULL, 
    [Course Description] NVARCHAR(255) NULL, 
    [Course Name (Short)] NVARCHAR(50) NULL, 
    [Credit Hours] DECIMAL(9, 2) NULL, 
    [Contact Hours] DECIMAL(9, 2) NULL, 
    [Course CIP] NCHAR(7) NULL, 
    [Course Type] NVARCHAR(25) NULL, 
    [Course Delivery Mode] NVARCHAR(100) NULL, 
    [Instructional Method] NVARCHAR(100) NULL, 
    [Campus] NVARCHAR(100) NULL, 
    [Building] NVARCHAR(100) NULL, 
    [Room] NVARCHAR(100) NULL, 
    [Developmental Course Flag] NCHAR(1) NULL, 
    [Class Meeting Days] NVARCHAR(100) NULL, 
    [Class Beginning Time] TIME NULL, 
    [Class Ending Time] TIME NULL, 
    [Total Enrollment] INT NULL, 
    [Total Enrollment - First Day] INT NULL, 
    [Total Enrollment - Census] NCHAR(10) NULL, 
    CONSTRAINT [PK_DimCourses] PRIMARY KEY ([Courses_Key]), 
    CONSTRAINT [FK_DimCourses_DimTerms] FOREIGN KEY ([Terms_Key]) REFERENCES [dw].[DimTerms]([Terms_Key])
)
