CREATE TABLE [dw].[DimStudents]
(
	[Students_Key] INT NOT NULL  IDENTITY, 
    [Campus ID] NCHAR(10) NULL, 
    [SSN] NCHAR(11) NULL, 
    [Alternate IDs] NVARCHAR(50) NULL, 
    [First Name] NVARCHAR(100) NULL, 
    [Middle Name] NVARCHAR(50) NULL, 
    [Last Name] NVARCHAR(100) NULL, 
    [Suffix] NVARCHAR(10) NULL, 
    [Prefix] NVARCHAR(10) NULL, 
    [Former Last Name] NVARCHAR(100) NULL, 
    [City] NVARCHAR(100) NULL, 
    [State] NVARCHAR(50) NULL, 
    [State Abbreviation] NVARCHAR(3) NULL, 
    [Zip Code] NVARCHAR(10) NULL, 
    [County Code] NVARCHAR(8) NULL, 
    [County] NVARCHAR(50) NULL, 
    [Country Code] NVARCHAR(5) NULL, 
    [Country] NVARCHAR(100) NULL, 
    [Residency Status] NVARCHAR(50) NULL, 
    [Birthdate] DATE NULL, 
	[Gender] NVARCHAR(10) NULL,
    [Race] NVARCHAR(50) NULL, 
    [Ethnicity] NVARCHAR(50) NULL, 
    [Veteran Type] NVARCHAR(50) NULL, 
    [Marital Status] NVARCHAR(50) NULL, 
    [Privacy Flag] NCHAR NULL, 
    [Directory Flag] NCHAR(1) NULL, 
    [Deceased Date] DATE NULL, 
    [BeginDate] DATETIME NULL, 
    [EndDate] DATETIME NULL, 
    CONSTRAINT [PK_DimStudents] PRIMARY KEY ([Students_Key])
)

GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'All students with an enrollment, program, or credential',
    @level0type = N'SCHEMA',
    @level0name = N'dw',
    @level1type = N'TABLE',
    @level1name = N'DimStudents',
    @level2type = NULL,
    @level2name = NULL