SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
DROP VIEW [history].[ELF_TRANSLATE_TABLES__ACTION_CODES]
GO
CREATE VIEW [history].[ELF_TRANSLATE_TABLES__ACTION_CODES] AS
SELECT [ELF.TRANSLATE.TABLES.ID]
       
, CAST(LTRIM(RTRIM(CA1.Item)) AS VARCHAR(10)) AS [ELFT.ACTION.CODES.1]
, CAST(LTRIM(RTRIM(CA2.Item)) AS VARCHAR(10)) AS [ELFT.ACTION.CODES.2]
, CAST(LTRIM(RTRIM(CA3.Item)) AS VARCHAR(10)) AS [ELFT.ACTION.CODES.3]
, CAST(LTRIM(RTRIM(CA4.Item)) AS VARCHAR(10)) AS [ELFT.ACTION.CODES.4]
     , CA1.ItemNumber AS ItemNumber
     , EffectiveDatetime
  FROM [history].[ELF_TRANSLATE_TABLES]
  
CROSS APPLY dw_util.DelimitedSplit8K([ELFT.ACTION.CODES.1],', ') CA1
CROSS APPLY dw_util.DelimitedSplit8K([ELFT.ACTION.CODES.2],', ') CA2
CROSS APPLY dw_util.DelimitedSplit8K([ELFT.ACTION.CODES.3],', ') CA3
CROSS APPLY dw_util.DelimitedSplit8K([ELFT.ACTION.CODES.4],', ') CA4
 WHERE COALESCE([ELFT.ORIG.CODES],'') != ''
       AND CA1.ItemNumber=CA2.ItemNumber
AND CA1.ItemNumber=CA3.ItemNumber
AND CA1.ItemNumber=CA4.ItemNumber

GO
