WITH cs AS (
	SELECT [COURSE.SECTIONS.ID]
	     , [SEC.MEETING]
	     , [SEC.COURSE]
	     , [SEC.TERM]
	     , [SEC.NO]
	     , [SEC.LOCATION]
      FROM [IERG].[history].[COURSE_SECTIONS]
	 WHERE [EffectiveDatetime] <= '02/23/2018'
	   AND ([ExpirationDatetime] is null
	       OR [ExpirationDatetime] > '02/23/2018')
	  AND  [SEC.TERM] IN ('2018SP', '2018CE1')
), csm AS (
	SELECT [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ID]
	     , [COURSE_SEC_MEETING].[CSM.COURSE.SECTION]
	     , [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ADDDATE]
		 , [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ADDOPR]
		 , [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.CHGDATE]
		 , [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.CHGOPR]
		 , [COURSE_SEC_MEETING].[CSM.START.DATE]
		 , [COURSE_SEC_MEETING].[CSM.START.TIME]
		 , [COURSE_SEC_MEETING].[CSM.END.DATE]
		 , [COURSE_SEC_MEETING].[CSM.END.TIME]
		 , [COURSE_SEC_MEETING__CSM_DAYS_ASSOC].[CSM.DAYS]
		 , [COURSE_SEC_MEETING].[CSM.BLDG]
		 , [COURSE_SEC_MEETING].[CSM.ROOM]
		 , [COURSE_SEC_MEETING].[CSM.INSTR.METHOD]
	  FROM [IERG].[history].[COURSE_SEC_MEETING]
	  LEFT JOIN [IERG].[history].[COURSE_SEC_MEETING__CSM_DAYS_ASSOC]
		   ON ([COURSE_SEC_MEETING__CSM_DAYS_ASSOC].[COURSE.SEC.MEETING.ID] = [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ID]
		       AND [COURSE_SEC_MEETING__CSM_DAYS_ASSOC].[EffectiveDatetime] = [COURSE_SEC_MEETING].[EffectiveDatetime])
	 WHERE [COURSE_SEC_MEETING].[EffectiveDatetime] <= '02/23/2018'
	   AND ([COURSE_SEC_MEETING].[ExpirationDatetime] is null
	        OR [COURSE_SEC_MEETING].[ExpirationDatetime] > '02/23/2018')
	   AND  [CSM.SEC.TERM] IN ('2018SP', '2018CE1')
), c AS (
	SELECT [COURSES.ID]
	     , [CRS.SUBJECT]
		 , [CRS.NO]
	  FROM [IERG].[history].[COURSES]
	 WHERE [EffectiveDatetime] <= '02/23/2018'
	   AND ([ExpirationDatetime] is null
	       OR [ExpirationDatetime] > '02/23/2018')
)
SELECT cs.[SEC.TERM]
	 , c.[CRS.SUBJECT]
	 , c.[CRS.NO]
	 , cs.[SEC.NO]
	 , csm.[COURSE.SEC.MEETING.ADDDATE]
	 , csm.[COURSE.SEC.MEETING.ADDOPR]
	 , csm.[COURSE.SEC.MEETING.CHGDATE]
	 , csm.[COURSE.SEC.MEETING.CHGOPR]
	 , csm.[CSM.START.DATE]
	 , csm.[CSM.START.TIME]
	 , csm.[CSM.END.DATE]
	 , csm.[CSM.END.TIME]
	 , csm.[CSM.DAYS]
	 , cs.[SEC.LOCATION]
	 , csm.[CSM.BLDG]
	 , csm.[CSM.ROOM]
	 , csm.[CSM.INSTR.METHOD]
  FROM cs
  LEFT JOIN csm ON (csm.[COURSE.SEC.MEETING.ID] = cs.[SEC.MEETING])
  LEFT JOIN c   ON (c.[COURSES.ID] = cs.[SEC.COURSE])
 WHERE cs.[SEC.TERM] IN ('2018SP', '2018CE1')
