WITH cs AS (
		SELECT [COURSE.SECTIONS.ID]
		     , [SEC.MEETING]
			 , [SEC.COURSE]
			 , [SEC.TERM]
			 , [SEC.NO]
			 , [SEC.LOCATION]
		  FROM [IERG].[history].[COURSE_SECTIONS]
		 WHERE [EffectiveDatetime] <= '02/23/2018'
	      AND ([ExpirationDatetime] is null
	           OR [ExpirationDatetime] > '02/23/2018')
	), csm AS (
		SELECT [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ID]
		      ,[COURSE_SEC_MEETING].[CSM.COURSE.SECTION]
			  ,[COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ADDDATE]
			  ,[COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ADDOPR]
			  ,[COURSE_SEC_MEETING].[COURSE.SEC.MEETING.CHGDATE]
			  ,[COURSE_SEC_MEETING].[COURSE.SEC.MEETING.CHGOPR]
			  ,[COURSE_SEC_MEETING].[CSM.START.DATE]
			  ,[COURSE_SEC_MEETING].[CSM.START.TIME]
			  ,[COURSE_SEC_MEETING].[CSM.END.DATE]
			  ,[COURSE_SEC_MEETING].[CSM.END.TIME]
			  ,[COURSE_SEC_MEETING__CSM_DAYS_ASSOC].[CSM.DAYS]
			  ,[COURSE_SEC_MEETING].[CSM.BLDG]
			  ,[COURSE_SEC_MEETING].[CSM.ROOM]
			  ,[COURSE_SEC_MEETING].[CSM.INSTR.METHOD]
		  FROM [IERG].[history].[COURSE_SEC_MEETING]
		  LEFT JOIN [IERG].[history].[COURSE_SEC_MEETING__CSM_DAYS_ASSOC]
		  	   ON ([COURSE_SEC_MEETING__CSM_DAYS_ASSOC].[COURSE.SEC.MEETING.ID] = [COURSE_SEC_MEETING].[COURSE.SEC.MEETING.ID]
					 AND [COURSE_SEC_MEETING__CSM_DAYS_ASSOC].[EffectiveDatetime] = [COURSE_SEC_MEETING].[EffectiveDatetime])
		 WHERE [COURSE_SEC_MEETING].[EffectiveDatetime] <= '02/23/2018'
	      AND ([COURSE_SEC_MEETING].[ExpirationDatetime] is null
	           OR [COURSE_SEC_MEETING].[ExpirationDatetime] > '02/23/2018')
	), c AS (
		SELECT [COURSES.ID]
			 , [CRS.SUBJECT]
			 , [CRS.NO]
		  FROM [IERG].[history].[COURSES]
		 WHERE [EffectiveDatetime] <= '02/23/2018'
	      AND ([ExpirationDatetime] is null
	           OR [ExpirationDatetime] > '02/23/2018')
	), lag AS (
		SELECT cs.*, c.*, csm.*,
			LAG(c.[CRS.NO]) OVER (ORDER BY c.[CRS.NO]) CRS_LAG
		FROM cs, c, csm
	)
	SELECT LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CRS.NO] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[SEC.TERM] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CRS.SUBJECT] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[SEC.NO] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[COURSE.SEC.MEETING.ADDDATE] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[COURSE.SEC.MEETING.ADDOPR] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[COURSE.SEC.MEETING.CHGDATE] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[COURSE.SEC.MEETING.CHGOPR] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CSM.START.DATE] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CSM.START.TIME] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CSM.END.DATE] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CSM.END.TIME] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(COALESCE(lag.[CSM.DAYS],'') + REPLICATE(' ', 1), 1)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[SEC.LOCATION] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CSM.BLDG] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CSM.ROOM] ELSE '' END + REPLICATE(' ', 10), 10)
		 , LEFT(CASE WHEN lag.[CRS.NO] <> lag.CRS_LAG THEN lag.[CSM.INSTR.METHOD] ELSE '' END + REPLICATE(' ', 10), 10)
		 , csm.[CSM.INSTR.METHOD]
	  FROM lag
	  LEFT JOIN csm ON (lag.[COURSE.SEC.MEETING.ID] = lag.[SEC.MEETING])
	  LEFT JOIN c   ON (lag.[COURSES.ID] = lag.[SEC.COURSE])
	 WHERE lag.[SEC.TERM] IN ('2018', '01') /*'2018SP'*/
;
/*
EXEC datamart.getCLASS_01 '2018', '01', '02/23/2018'

--, '2018SP'
*/