CREATE TABLE [input].[Persons] (
    [PersonsID]                       INT            NOT NULL,
    [CampusID]                       VARCHAR (10)   NULL,
    [Social Security Number]         VARCHAR (11)   NULL,
    [Alt IDs]                        VARCHAR (25)   NULL,
    [Last Name]                      VARCHAR (100)  NULL,
    [First Name]                     VARCHAR (50)   NULL,
    [Middle Name]                    VARCHAR (50)   NULL,
    [Suffix]                         VARCHAR (5)    NULL,
    [Former Last Name]               VARCHAR (1720) NULL,
    [Address Lines]                  VARCHAR (200)  NULL,
    [City]                           VARCHAR (50)   NULL,
    [State Abbreviation]             VARCHAR (2)    NULL,
    [Zip]                            VARCHAR (10)   NULL,
    [County_ID]                      VARCHAR (8)    NULL,
    [Birthdate]                      DATE           NULL,
    [Home Phone 1]                   VARCHAR (12)   NULL,
    [Home Phone 2]                   VARCHAR (12)   NULL,
    [Cell Phone 1]                   VARCHAR (12)   NULL,
    [Cell Phone 2]                   VARCHAR (12)   NULL,
    [EmailPersonal]                  VARCHAR (50)   NULL,
    [EmailPersonalAlternate]         VARCHAR (50)   NULL,
    [EmailCampus]                    VARCHAR (50)   NULL,
    [Ethnicity Code]                 VARCHAR (1)    NULL,
    [Ethnicity]                      VARCHAR (35)   NULL,
    [Gender Code]                    VARCHAR (1)    NULL,
    [Gender]                         VARCHAR (10)   NULL,
    [Citizen]                        VARCHAR (3)    NULL,
    [Country Code]                   VARCHAR (3)    NULL,
    [Residency Status Code]          VARCHAR (11)   NULL,
    [Residency Status Date]          VARCHAR (34)   NULL,
    [Residence Country Code]         VARCHAR (2)    NULL,
    [Residence State Abbreviation]   VARCHAR (2)    NULL,
    [Overall Employment Status Code] VARCHAR (2)    NULL,
    [Veteran Type Code]              VARCHAR (8)    NULL,
    [Deceased Date]                  DATE           NULL,
    [Marital Status Code]            VARCHAR (1)    NULL,
    [Privacy Flag Code]              VARCHAR (1)    NULL,
    [Directory Flag Code]            VARCHAR (2)    NULL,
    [Visa Type Code]                 VARCHAR (2)    NULL,
    [Entry Date]                     DATE           NULL,
    [Person Add Operator]            VARCHAR (8)    NULL,
    [Last Changed]                   DATE           NULL,
    [Person Change Operator]         VARCHAR (8)    NULL,
    [Alien Status Code]              VARCHAR (1)    NULL,
    [RECORD_HASH]                    VARCHAR (32)   NULL
);

