CREATE TABLE [input].[ProgramProgress] (
    [ProgramProgressID]       INT            IDENTITY (1, 1) NOT NULL,
    [PersonsID]                NUMERIC (11)   NULL,
    [CampusID]                VARCHAR (7)    NULL,
    [First Name]              VARCHAR (50)   NULL,
    [Middle Name]             VARCHAR (50)   NULL,
    [Last Name]               VARCHAR (100)  NULL,
    [Gender Code]             VARCHAR (1)    NULL,
    [Gender]                  VARCHAR (10)   NULL,
    [Race Code]               VARCHAR (1)    NULL,
    [Race]                    VARCHAR (35)   NULL,
    [Program Code]            VARCHAR (10)   NULL,
    [Program Name]            VARCHAR (100)  NULL,
    [Credential]              VARCHAR (10)   NULL,
    [Credential Type]         VARCHAR (20)   NULL,
    [Major Name]              VARCHAR (100)  NULL,
    [Major CIP]               VARCHAR (7)    NULL,
    [Primary Program Flag]    VARCHAR (1)    NULL,
    [Start Date MV]           VARCHAR (50)   NULL,
    [End Date MV]             VARCHAR (50)   NULL,
    [Status MV]               VARCHAR (20)   NULL,
    [Status Date MV]          VARCHAR (100)  NULL,
    [Catalog]                 VARCHAR (4)    NULL,
    [Academic Level]          VARCHAR (3)    NULL,
    [Program Start Date]      DATE           NULL,
    [Program Minimum GPA]     NUMERIC (8, 2) NULL,
    [Program Minimum Credits] NUMERIC (8, 2) NULL,
    [Graduation Allowed Flag] VARCHAR (1)    NULL,
    [Career Goal]             VARCHAR (50)   NULL,
    [Previous Graduate Date]  DATE           NULL,
    [Admission Status]        VARCHAR (1)    NULL,
    [Program Credits]         NUMERIC (8, 2) NULL,
    [Cumulative GPA]          NUMERIC (8, 2) NULL,
    [Total College Credits]   NUMERIC (8, 2) NULL,
    [Academic Standing MV]    VARCHAR (7)    NULL,
    [Most Recent Term]        VARCHAR (7)    NULL,
    [Term Start Date MV]      VARCHAR (200)  NULL,
    [Term End Date MV]        VARCHAR (200)  NULL, 
    CONSTRAINT [PK_ProgramProgress] PRIMARY KEY ([ProgramProgressID])
);

