CREATE TABLE [input].[Student_Courses] (
    [StudentCourseID]          INT           NOT NULL,
    [PersonID]                 INT           NULL,
    [Campus_ID]                VARCHAR (10)  NULL,
    [Term Code]                VARCHAR (10)  NULL,
    [Subject]                  VARCHAR (255) NULL,
    [Course]                   VARCHAR (255) NULL,
    [Section]                  VARCHAR (255) NULL,
    [Title]                    VARCHAR (255) NULL,
    [Instructor]               VARCHAR (255) NULL,
    [First Name]               VARCHAR (255) NULL,
    [Last Name]                VARCHAR (255) NULL,
    [Gender Code]              CHAR (1)      NULL,
    [Gender]                   VARCHAR (20)  NULL,
    [County Name]              VARCHAR (255) NULL,
    [Residence State]          VARCHAR (100) NULL,
    [Ethnicity]                VARCHAR (100) NULL,
    [Birthdate]                DATE          NULL,
    [Student Status]           VARCHAR (2)   NULL,
    [Grade]                    VARCHAR (2)   NULL,
    [Term]                     VARCHAR (25)  NULL,
    [Term Type]                CHAR (2)      NULL,
    [Academic Year]            CHAR (9)      NULL,
    [Reporting Academic Year]  CHAR (9)      NULL,
    [Year]                     INT           NULL,
    [Reporting Year]           INT           NULL,
    [Reporting Code]           INT           NULL,
    [Reporting Code Alternate] INT           NULL,
    [Term Sort Order]          INT           NULL,
    [RECORD_HASH]              CHAR (64)     NULL, 
    CONSTRAINT [PK_Student_Courses] PRIMARY KEY ([StudentCourseID])
);

