CREATE TABLE [input].[StudentCredentials] (
    [StudentCredentialsID]                     INT            NOT NULL,
    [PersonsId]                                 INT            NULL,
    [CampusID]                                 NVARCHAR (10)  NULL,
    [First Name]                               NVARCHAR (35)  NULL,
    [Middle Name]                              NVARCHAR (35)  NULL,
    [Last Name]                                NVARCHAR (35)  NOT NULL,
    [Suffix]                                   NVARCHAR (10)  NULL,
    [Prefix]                                   NVARCHAR (30)  NULL,
    [Age]                                      INT            NULL,
    [Gender Code]                              NVARCHAR (2)   NULL,
    [Gender]                                   NVARCHAR (10)  NULL,
    [Race Code]                                NVARCHAR (2)   NULL,
    [Race]                                     NVARCHAR (20)  NULL,
    [Hispanic or Latino]                       NVARCHAR (3)   NULL,
    [City]                                     NVARCHAR (30)  NULL,
    [State Code]                               NVARCHAR (2)   NULL,
    [Zip Code]                                 NVARCHAR (17)  NULL,
    [County Code]                              NVARCHAR (5)   NULL,
    [County]                                   NVARCHAR (30)  NULL,
    [Country Code]                             NVARCHAR (5)   NULL,
    [Country]                                  NVARCHAR (50)  NULL,
    [Latitude]                                 NVARCHAR (20)  NULL,
    [Longitude]                                NVARCHAR (20)  NULL,
    [State of Residence Code]                  NVARCHAR (2)   NULL,
    [State of Residence]                       NVARCHAR (20)  NULL,
    [Citizenship]                              NVARCHAR (10)  NULL,
    [Residency]                                NVARCHAR (10)  NULL,
    [Initial Cohort]                           NVARCHAR (7)   NULL,
    [Program Code]                             NVARCHAR (10)  NULL,
    [Program Name]                             NVARCHAR (100) NULL,
    [Credential]                               NVARCHAR (10)  NULL,
    [Credential Type]                          NVARCHAR (10)  NULL,
    [Major Code]                               NVARCHAR (10)  NULL,
    [Major Name]                               NVARCHAR (100) NULL,
    [Major CIP]                                NVARCHAR (7)   NULL,
    [Honors]                                   NVARCHAR (255) NULL,
    [Award Date]                               DATE           NULL,
    [First Term in Program]                    NVARCHAR (7)   NULL,
    [Program Hours Attempted]                  DECIMAL (9, 2) NULL,
    [Program Hours Completed]                  DECIMAL (9, 2) NULL,
    [Program GPA]                              DECIMAL (9, 2) NULL,
    [Total Hours Attempted]                    DECIMAL (9, 2) NULL,
    [Total Hours Completed]                    DECIMAL (9, 2) NULL,
    [Total GPA]                                DECIMAL (9, 2) NULL,
    [First-time Postsecondary Student]         NVARCHAR (3)   NULL,
    [Entry Date Into Postsecondary]            DATE           NULL,
    [Initial Enrollment Term]                  NVARCHAR (7)   NULL,
    [Transfer Ready]                           NVARCHAR (3)   NULL,
    [Any Distance Education Course Enrollment] NVARCHAR (3)   NULL,
    [Developmental Education Status Code]      NVARCHAR (5)   NULL,
    [Developmental Education Status]           NVARCHAR (50)  NULL,
    [Term Code]                                NVARCHAR (7)   NULL,
    [Term]                                     NVARCHAR (10)  NULL,
    [Term Type]                                NVARCHAR (2)   NULL,
    [Term Abbreviation]                        NVARCHAR (3)   NULL,
    [Academic Year]                            NVARCHAR (9)   NULL,
    [Reporting Academic Year]                  NVARCHAR (9)   NULL,
    [Year]                                     INT            NULL,
    [Reporting Year]                           INT            NULL,
    [Reporting Code]                           INT            NULL,
    [Reporting Code Alternate]                 INT            NULL,
    [Term Sort Order]                          INT            NULL,
    [RECORD_HASH]                              NVARCHAR (64)  NULL
);

