CREATE TABLE [input].[StudentCourses] (
    [StudentCoursesID]                   INT             NOT NULL IDENTITY,
    [CoursesID]                          INT             NULL,
    [PersonsID]                          INT             NULL,
    [CampusID]                          NVARCHAR (10)   NULL,
    [Campus Course ID]                  NVARCHAR (60)   NULL,
    [Course]                            NVARCHAR (60)   NULL,
    [Subject Code]                      NVARCHAR (10)   NULL,
    [Course Number]                     NVARCHAR (10)   NULL,
    [Section Number]                    NVARCHAR (10)   NULL,
    [Course Title]                      NVARCHAR (255)  NULL,
    [Course Short Title]                NVARCHAR (50)   NULL,
    [Credit Hours]                      DECIMAL (9, 2)  NULL,
    [Contact Hours]                     DECIMAL (9, 2)  NULL,
    [Term Code]                         NVARCHAR (7)    NULL,
    [Term]                              NVARCHAR (20)   NULL,
    [Term Type]                         NVARCHAR (2)    NULL,
    [Term Abbreviation]                 NVARCHAR (3)    NULL,
    [Academic Year]                     NVARCHAR (9)    NULL,
    [Reporting Academic Year]           NVARCHAR (9)    NULL,
    [Year]                              INT             NULL,
    [Reporting Year]                    INT             NULL,
    [Reporting Code]                    INT             NULL,
    [Reporting Code Alternate]          INT             NULL,
    [Term Sort Order]                   INT             NULL,
    [Instructor]                        NVARCHAR (255)  NULL,
    [Department Name]                   NVARCHAR (50)   NULL,
    [College Name]                      NVARCHAR (50)   NULL,
    [Course CIP]                        NVARCHAR (7)    NULL,
    [Course Type]                       NVARCHAR (25)   NULL,
    [Course Delivery Mode]              NVARCHAR (100)  NULL,
    [Instructional Method]              NVARCHAR (100)  NULL,
    [Campus]                            NVARCHAR (100)  NULL,
    [Building]                          NVARCHAR (100)  NULL,
    [Room]                              NVARCHAR (100)  NULL,
    [Is Developmental Course]           NVARCHAR (3)    NULL,
    [Class Meeting Days]                NVARCHAR (60)   NULL,
    [Class Beginning Time]              TIME (7)        NULL,
    [Class Ending Time]                 TIME (7)        NULL,
    [Time Day Identifier]               NVARCHAR (40)   NULL,
    [Total Enrollment]                  INT             NULL,
    [Total Enrollment - First Day]      INT             NULL,
    [Total Enrollment - Census]         INT             NULL,
    [Registration Status]               NVARCHAR (20)   NULL,
    [Registration Status Date]          DATE            NULL,
    [Initial Registration Status]       NVARCHAR (20)   NULL,
    [Initial Registration Status Date]  DATE            NULL,
    [Grade]                             NVARCHAR (1)    NULL,
    [Quality Points]                    DECIMAL (9, 2)  NULL,
    [Passing Grade]                     NVARCHAR (3)    NULL,
    [Age]                               INT             NULL,
    [Gender]                            NVARCHAR (10)   NULL,
    [Race]                              NVARCHAR (20)   NULL,
    [Hispanic or Latino]                NVARCHAR (3)    NULL,
    [Citizenship]                       NVARCHAR (10)   NULL,
    [Tribal Affiliation]                NVARCHAR (50)   NULL,
    [City]                              NVARCHAR (30)   NULL,
    [State Code]                        NVARCHAR (2)    NULL,
    [Postal Code]                       NVARCHAR (17)   NULL,
    [County]                            NVARCHAR (30)   NULL,
    [Country]                           NVARCHAR (50)   NULL,
    [State of Residence]                NVARCHAR (20)   NULL,
    [Number of People in Family]        INT             NULL,
    [Number of People in Household]     INT             NULL,
    [Number of Dependents]              INT             NULL,
    [Family Income]                     DECIMAL (10, 2) NULL,
    [Highest Education Level Completed] NVARCHAR (50)   NULL,
    [Paternal Education Level]          NVARCHAR (50)   NULL,
    [Maternal Education Level]          NVARCHAR (50)   NULL,
    [Military Active Student]           NVARCHAR (10)   NULL,
    [Military Branch]                   NVARCHAR (100)  NULL,
    [Employed While Enrolled]           NVARCHAR (3)    NULL,
    [Employed After Exit]               NVARCHAR (3)    NULL,
    [RECORD_HASH]                       NVARCHAR (64)   NULL, 
    CONSTRAINT [FK_StudentCourses_Persons] FOREIGN KEY ([PersonsID]) REFERENCES [Persons]([PersonsID]), 
    CONSTRAINT [FK_StudentCourses_Courses] FOREIGN KEY ([CoursesID]) REFERENCES [Courses]([CoursesID])
);

