CREATE TABLE [input].[StudentPrograms] (
    [StudentProgramsID]                         INT             IDENTITY (1, 1) NOT NULL,
    [ProgramsID]                                INT             NULL,
    [PersonsID]                                 INT             NULL,
    [CampusID]                                 NVARCHAR (10)   NULL,
    [Program Code]                             NVARCHAR (10)   NULL,
    [Program Name]                             NVARCHAR (100)  NULL,
    [Credential]                               NVARCHAR (10)   NULL,
    [Credential Type]                          NVARCHAR (10)   NULL,
    [Major Code]                               NVARCHAR (10)   NULL,
    [Major Name]                               NVARCHAR (100)  NULL,
    [Major CIP]                                NVARCHAR (7)    NULL,
    [Catalog]                                  NVARCHAR (4)    NULL,
    [First Term in Program]                    NVARCHAR (7)    NULL,
    [Is First Term in Program]                 NVARCHAR (3)    NULL,
    [Program Hours Attempted]                  DECIMAL (9, 2)  NULL,
    [Program Hours Completed]                  DECIMAL (9, 2)  NULL,
    [Program GPA]                              DECIMAL (9, 2)  NULL,
    [Term Code]                                NVARCHAR (7)    NULL,
    [Term]                                     NVARCHAR (10)   NULL,
    [Term Type]                                NVARCHAR (2)    NULL,
    [Term Abbreviation]                        NVARCHAR (3)    NULL,
    [Academic Year]                            NVARCHAR (9)    NULL,
    [Reporting Academic Year]                  NVARCHAR (9)    NULL,
    [Year]                                     INT             NULL,
    [Reporting Year]                           INT             NULL,
    [Reporting Code]                           INT             NULL,
    [Reporting Code Alternate]                 INT             NULL,
    [Term Sort Order]                          INT             NULL,
    [Birthdate]                                DATE            NULL,
    [Age]                                      INT             NULL,
    [Gender Code]                              NVARCHAR (2)    NULL,
    [Gender]                                   NVARCHAR (10)   NULL,
    [Race Code]                                NVARCHAR (2)    NULL,
    [Race]                                     NVARCHAR (20)   NULL,
    [Hispanic or Latino]                       NVARCHAR (3)    NULL,
    [Citizenship]                              NVARCHAR (10)   NULL,
    [Tribal Affiliation]                       NVARCHAR (50)   NULL,
    [City]                                     NVARCHAR (30)   NULL,
    [State Code]                               NVARCHAR (2)    NULL,
    [Postal Code]                              NVARCHAR (17)   NULL,
    [County Code]                              NVARCHAR (5)    NULL,
    [County]                                   NVARCHAR (30)   NULL,
    [Country Code]                             NVARCHAR (5)    NULL,
    [Country]                                  NVARCHAR (50)   NULL,
    [State of Residence Code]                  NVARCHAR (2)    NULL,
    [State of Residence]                       NVARCHAR (20)   NULL,
    [Number of People in Family]               INT             NULL,
    [Number of People in Household]            INT             NULL,
    [Number of Dependents]                     INT             NULL,
    [Family Income]                            DECIMAL (10, 2) NULL,
    [Highest Education Level Completed]        NVARCHAR (50)   NULL,
    [Paternal Education Level]                 NVARCHAR (50)   NULL,
    [Maternal Education Level]                 NVARCHAR (50)   NULL,
    [Military Active Student]                  NVARCHAR (10)   NULL,
    [Military Branch]                          NVARCHAR (100)  NULL,
    [Employed While Enrolled]                  NVARCHAR (3)    NULL,
    [Employed After Exit]                      NVARCHAR (3)    NULL,
    [Cohort]                                   NVARCHAR (7)    NULL,
    [First-time Postsecondary Student]         NVARCHAR (3)    NULL,
    [Entry Date Into Postsecondary]            DATE            NULL,
    [Initial Enrollment Term]                  NVARCHAR (7)    NULL,
    [Transfer Ready]                           NVARCHAR (3)    NULL,
    [Total Hours Attempted]                    DECIMAL (9, 2)  NULL,
    [Total Hours Completed]                    DECIMAL (9, 2)  NULL,
    [Total GPA]                                DECIMAL (9, 2)  NULL,
    [Any Distance Education Course Enrollment] NVARCHAR (3)    NULL,
    [Developmental Education Status Code]      NVARCHAR (5)    NULL,
    [Developmental Education Status]           NVARCHAR (50)   NULL,
    [Financial Aid Applicant]                  NVARCHAR (3)    NULL,
    [Financial Need]                           DECIMAL (9, 2)  NULL,
    [Title IV Participant and Recipient]       NVARCHAR (3)    NULL,
    [Financial Aid Income Level]               DECIMAL (9, 2)  NULL,
    [Financial Aid Veterans Benefit Status]    NVARCHAR (30)   NULL,
    [Financial Aid Veterans Benefit Type]      NVARCHAR (30)   NULL,
    [RECORD_HASH]                              NVARCHAR (64)   NULL,
    CONSTRAINT [PK_StudentPrograms] PRIMARY KEY CLUSTERED ([StudentProgramsID] ASC)
);

